name: vigor22
dependencies:
  - python>=3.7
  - geopandas=0.12.1
  - pip
  - pip:
    - fastapi
    - uvicorn
    - python-multipart
    - owslib
    - point-in-geojson-jaluebbe
    - smbus2
    - orjson
